package org.usfirst.frc.team2733.robot.enumerations;

public enum PortsEnum {
	
	//conrollers
	JOYSTICK_ONE (0),
	JOYSTICK_TWO (1),
	
	//motors
	SHOOTER (4),
	CLIMBER (5),
	INTAKE (6), 
	
	FRONT_LEFT_DRIVE_MOTOR (13),
	FRONT_RIGHT_DRIVE_MOTOR (11),
	BACK_LEFT_DRIVE_MOTOR (17),
	BACK_RIGHT_DRIVE_MOTOR (16),
	
	FRONT_LEFT_ROTATION_MOTOR (14),
	FRONT_RIGHT_ROTATION_MOTOR (12),
	BACK_LEFT_ROTATION_MOTOR (18),
	BACK_RIGHT_ROTATION_MOTOR (15),

	//Encoders
		//digital
	FRONT_LEFT_ROTATION_DIGITAL_ENCODER_ONE (0),
	FRONT_RIGHT_ROTATION_DIGITAL_ENCODER_ONE (2),
	BACK_LEFT_ROTATION_DIGITAL_ENCODER_ONE (4),
	BACK_RIGHT_ROTATION_DIGITAL_ENCODER_ONE (6),
	
	FRONT_LEFT_ROTATION_DIGITAL_ENCODER_TWO (1),
	FRONT_RIGHT_ROTATION_DIGITAL_ENCODER_TWO (3),
	BACK_LEFT_ROTATION_DIGITAL_ENCODER_TWO (5),
	BACK_RIGHT_ROTATION_DIGITAL_ENCODER_TWO (7),
		
		//analog
	FRONT_RIGHT_ROTATION_ANALOG_ENCODER (0),
	BACK_RIGHT_ROTATION_ANALOG_ENCODER (1),
	FRONT_LEFT_ROTATION_ANALOG_ENCODER (2),
	BACK_LEFT_ROTATION_ANALOG_ENCODER (3);
	
	private int port;
	
	PortsEnum(int port){
		this.port = port;
	}
	
	public int getPort(){
		return port;
	}
	
}
