package org.usfirst.frc.team2733.robot.enumerations;

public enum PortsEnum {

	// Motors
	SHOOTER (1),
    BALL_RELEASE (0),
	CLIMBER (2),
	INTAKE (3),

	FRONT_LEFT_DRIVE_MOTOR (18),
	FRONT_RIGHT_DRIVE_MOTOR (16),
	BACK_LEFT_DRIVE_MOTOR (12),
	BACK_RIGHT_DRIVE_MOTOR (11),

	FRONT_LEFT_ROTATION_MOTOR (5),
	FRONT_RIGHT_ROTATION_MOTOR (15),
	BACK_LEFT_ROTATION_MOTOR (14),
	BACK_RIGHT_ROTATION_MOTOR (13),
	 *
	 */
	FRONT_LEFT_DRIVE_MOTOR (4),
	FRONT_RIGHT_DRIVE_MOTOR (0),
	BACK_LEFT_DRIVE_MOTOR (6),
	BACK_RIGHT_DRIVE_MOTOR (2),

	FRONT_LEFT_ROTATION_MOTOR (5),
	FRONT_RIGHT_ROTATION_MOTOR (1),
	BACK_LEFT_ROTATION_MOTOR (7),
	BACK_RIGHT_ROTATION_MOTOR (3),

	// Analog encoders
	FRONT_RIGHT_ROTATION_ANALOG_ENCODER (0),
	BACK_RIGHT_ROTATION_ANALOG_ENCODER (1),
	FRONT_LEFT_ROTATION_ANALOG_ENCODER (2),
	BACK_LEFT_ROTATION_ANALOG_ENCODER (3);

	private int port;

	PortsEnum(int port) {
		this.port = port;
	}

	public int getPort() {
		return port;
	}

}
