package org.usfirst.frc.team2733.robot.enumerations;

public enum PortsEnum {

	JOYSTICK_ONE (0),
	JOYSTICK_TWO (0),
	
	FRONT_RIGHT_DRIVE_MOTOR (0),
	BACK_RIGHT_DRIVE_MOTOR (0),
	FRONT_LEFT_DRIVE_MOTOR (0),
	BACK_LEFT_DRIVE_MOTOR (0),
	
	FRONT_RIGHT_ROTATION_MOTOR (0),
	BACK_RIGHT_ROTATION_MOTOR (0),
	FRONT_LEFT_ROTATION_MOTOR (0),
	BACK_LEFT_ROTATION_MOTOR (0),

	FRONT_RIGHT_ROTATION_DIGITAL_ENCODER_ONE (0),
	BACK_RIGHT_ROTATION_DIGITAL_ENCODER_ONE (0),
	FRONT_LEFT_ROTATION_DIGITAL_ENCODER_ONE (0),
	BACK_LEFT_ROTATION_DIGITAL_ENCODER_ONE (0),
	
	FRONT_RIGHT_ROTATION_DIGITAL_ENCODER_TWO (0),
	BACK_RIGHT_ROTATION_DIGITAL_ENCODER_TWO (0),
	FRONT_LEFT_ROTATION_DIGITAL_ENCODER_TWO (0),
	BACK_LEFT_ROTATION_DIGITAL_ENCODER_TWO (0),

	FRONT_RIGHT_ROTATION_ANALOG_ENCODER (0),
	BACK_RIGHT_ROTATION_ANALOG_ENCODER (0),
	FRONT_LEFT_ROTATION_ANALOG_ENCODER (0),
	BACK_LEFT_ROTATION_ANALOG_ENCODER (0);
	
	private int port;
	
	PortsEnum(int port){
		this.port = port;
	}
	
	public int getPort(){
		return port;
	}
	
}
